<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.oracle.weblogic.migration</groupId>
  <artifactId>oci-weblogic-migration</artifactId>
  <version>0.1</version>
  <name>Oracle WebLogic Server Migration Tool</name>
  <description>A framework and set of tools to perform domain creation/changes.</description>
  <url>https://github.com/oracle-quickstart/oci-weblogic-migration</url>
  <inceptionYear>2024</inceptionYear>
  <licenses>
    <license>
      <name>The Universal Permissive License (UPL), Version 1.0</name>
      <url>https://oss.oracle.com/licenses/upl/</url>
      <distribution>repo</distribution>
    </license>
    <license>
      <name>The 3-Clause BSD License</name>
      <url>https://opensource.org/licenses/BSD-3-Clause</url>
      <distribution>repo</distribution>
      <comments>The Antlr Project license</comments>
    </license>
  </licenses>
  <properties>
    <!--
        Hack to get around Maven bug so that we can inject the build timestamp into the version class
     -->
    <weblogic.deploy.build.timestamp>${maven.build.timestamp}</weblogic.deploy.build.timestamp>
    <maven.build.timestamp.format>MMM dd, yyyy HH:mm z</maven.build.timestamp.format>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.7</maven.compiler.source>
    <maven.compiler.target>1.7</maven.compiler.target>
    <maven.compiler.testSource>1.8</maven.compiler.testSource>
    <maven.compiler.testTarget>1.8</maven.compiler.testTarget>
    <weblogic-migration-installer-name>weblogic-migration</weblogic-migration-installer-name>
    <skipTests>false</skipTests>
    <antlr.version>4.9.3</antlr.version>
    <snakeyaml.version>2.2</snakeyaml.version>
    <picocli.version>4.7.5</picocli.version>
    <sshj.version>0.38.0</sshj.version>
    <eddsa.version>0.3.0</eddsa.version>
    <slf4j.version>2.0.13</slf4j.version>
    <jzlib.version>1.1.3</jzlib.version>
    <asn.one.version>0.6.0</asn.one.version>
    <jline.version>3.26.1</jline.version>
    <jansi.version>2.4.1</jansi.version>
    <junit.version>5.10.2</junit.version>
    <oci.sdk.version>3.49.0</oci.sdk.version>
  </properties>
  <dependencies>
    <dependency>
      <groupId>com.oracle.weblogic.lifecycle</groupId>
      <artifactId>weblogic-deploy</artifactId>
      <version>4.2.0</version>
    </dependency>
    <dependency>
      <groupId>info.picocli</groupId>
      <artifactId>picocli</artifactId>
      <version>4.7.5</version>
    </dependency>
    <dependency>
      <groupId>com.oracle.oci.sdk</groupId>
      <artifactId>oci-java-sdk-objectstorage-extensions</artifactId>
      <version>3.49.0</version>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-install-plugin</artifactId>
        <version>3.0.0-M1</version>
        <configuration>
          <groupId>com.oracle.weblogic.lifecycle</groupId>
          <artifactId>weblogic-deploy</artifactId>
          <version>4.2.0</version>
          <packaging>jar</packaging>
          <file>${basedir}/../../deps/wdt/lib/weblogic-deploy-core.jar</file>
          <generatePom>true</generatePom>
        </configuration>
        <executions>
          <execution>
            <id>install-jar-lib</id>
            <goals>
              <goal>install-file</goal>
            </goals>
            <phase>validate</phase>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>


</project>
