#Copyright (c) 2024, 2025 Oracle Corporation and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl

locals {

  inventory_file_name = format("%s/%s/%s", path.module, var.wls_discovery_folder, var.wls_discovery_filename)
  wls_data            = jsondecode(file(local.inventory_file_name))
  wlsserver_cloud_init = var.wlsserver_cloud_init_configure ? [{
    content_type = "text/x-shellscript",
    content      = var.wlsserver_cloud_init_byon
  }] : []
  db_strategy_is_atp = local.datasources == null ? false : anytrue([for _, v in local.datasources : v.is_atp])
  db_strategy_is_edit_string_atp = local.datasources == null ? false : anytrue([
  for _, v in local.datasources : can(regex("adb", v.connection_string))])
  network_compartment_id = var.network_compartment_id == "" ? var.compartment_ocid : var.network_compartment_id

  db_strategy_0_is_atp_db = local.datasources == null ? false : local.datasources[0].is_atp
  db_strategy_0_is_oci_db = local.datasources == null ? false : local.datasources[0].is_oci_db
  // Criteria for VCN peering:
  // 1. Only when both create_vcn is true and DB VCN ID is provided (either oci_db_existing_vcn_id_0 or atp_db_existing_vcn_id_0)
  // 2. or when both WLS VCN ID is provided and DB VCN ID is provided (either oci_db_existing_vcn_id_0 or atp_db_existing_vcn_id_0) and they are different IDs,

  oci_db_network_comp_id_0 = local.db_strategy_0_is_oci_db ? local.datasources[0].oci_db.network_compartment_id : ""
  oci_db_existing_vcn_id_0 = local.db_strategy_0_is_oci_db ? local.datasources[0].oci_db.existing_vcn_id : ""
  oci_db_subnet_id_0       = local.db_strategy_0_is_oci_db ? local.datasources[0].oci_db.subnet_id : ""

  atp_has_private_endpoints_0 = local.db_strategy_0_is_atp_db ? local.datasources[0].atp_db.is_atp_with_private_endpoints : false
  atp_db_network_comp_id_0    = local.db_strategy_0_is_atp_db ? local.datasources[0].atp_db.network_compartment_id : ""
  atp_db_existing_vcn_id_0    = local.db_strategy_0_is_atp_db ? local.datasources[0].atp_db.existing_vcn_id : ""
  atp_db_subnet_id_0          = local.db_strategy_0_is_atp_db ? local.datasources[0].atp_db.subnet_id : ""

  db_network_compartment_id = local.datasources == null ? "" : (local.db_strategy_0_is_atp_db && local.atp_has_private_endpoints_0 ? local.atp_db_network_comp_id_0 : (local.db_strategy_0_is_oci_db ? local.oci_db_network_comp_id_0 : ""))
  db_existing_vcn_id        = local.datasources == null ? "" : (local.db_strategy_0_is_atp_db && local.atp_has_private_endpoints_0 ? local.atp_db_existing_vcn_id_0 : (local.db_strategy_0_is_oci_db ? local.oci_db_existing_vcn_id_0 : ""))
  db_subnet_id              = local.datasources == null ? "" : (local.db_strategy_0_is_atp_db && local.atp_has_private_endpoints_0 ? local.atp_db_subnet_id_0 : (local.db_strategy_0_is_oci_db ? local.atp_db_subnet_id_0 : ""))

  new_vcn_and_oci_db                    = local.db_strategy_0_is_oci_db && var.create_vcn ? true : false
  existing_vcn_and_oci_db_different_vcn = local.db_strategy_0_is_oci_db && var.vcn_id != "" && var.vcn_id != local.oci_db_existing_vcn_id_0 ? true : false

  new_vcn_and_atp_db_private_endpoint                    = local.db_strategy_0_is_atp_db && var.create_vcn && local.atp_has_private_endpoints_0 ? true : false
  existing_vcn_and_atp_db_private_endpoint_different_vcn = local.db_strategy_0_is_atp_db && var.vcn_id != "" && local.atp_has_private_endpoints_0 && (var.vcn_id != local.atp_db_existing_vcn_id_0) ? true : false

  is_vcn_peering = local.db_strategy_0_is_atp_db || local.db_strategy_0_is_oci_db ? (local.new_vcn_and_oci_db || local.new_vcn_and_atp_db_private_endpoint || local.existing_vcn_and_oci_db_different_vcn || local.existing_vcn_and_atp_db_private_endpoint_different_vcn) : false
}

#Code has become a single module due:
# - future version to split UI, tf-cli and base module.
# - Dynamic Terraform code generated by datasources
#Keeping the base module as an separate github module

module "wls" {
  #source    = "github.com/oracle-quickstart/oci-weblogic-migration.git?ref=5.x&depth=1"
  source             = "./iac"
  providers          = { oci.home = oci.home }
  wls_inventory_data = local.wls_data
  # Identity
  tenancy_id             = var.tenancy_ocid
  compartment_id         = var.compartment_ocid
  network_compartment_id = var.network_compartment_id

  create_iam_resources         = var.create_oci_policies
  create_iam_tag_namespace     = var.create_iam_tag_namespace
  create_iam_defined_tags      = var.create_iam_tag_namespace || var.create_iam_defined_tags
  use_defined_tags             = var.use_defined_tags
  tag_namespace                = var.tag_namespace
  create_iam_autoscaler_policy = "never"
  #   create_iam_wlsserver_policy     = var.create_iam_wlsserver_policy ? "always" : "never"

  #Network
  # Network
  create_vcn                  = var.create_vcn
  vcn_id                      = var.vcn_id
  vcn_cidrs                   = split(",", var.vcn_cidrs)
  vcn_create_internet_gateway = var.vcn_create_internet_gateway ? "always" : "never"
  vcn_create_nat_gateway      = var.vcn_create_nat_gateway ? "always" : "never"
  vcn_create_service_gateway  = var.vcn_create_service_gateway ? "always" : "never"
  vcn_name                    = var.vcn_name
  vcn_dns_label               = var.vcn_dns_label
  assign_dns                  = var.assign_dns
  ig_route_table_id           = var.ig_route_table_id
  local_peering_gateways      = var.local_peering_gateways
  lockdown_default_seclist    = var.lockdown_default_seclist
  create_drg                  = var.create_drg
  drg_id                      = var.drg_id
  drg_display_name            = var.drg_display_name
  wlsserver_subnet_cidr       = var.wlsserver_subnet_cidr

  subnets = {
    bastion = {
      create = var.bastion_subnet_create ? "always" : "never",
      cidr   = var.bastion_subnet_cidr,
      id     = var.bastion_subnet_id
    }

    #    operator = {
    #      create  = "never",  #future release
    #      newbits = var.operator_subnet_newbits,
    #      id      = var.operator_subnet_id
    #    }
    int_lb = {
      create  = var.int_lb_subnet_create ? "always" : "never",
      newbits = var.int_lb_subnet_newbits,
      id      = var.int_lb_subnet_id
    }

    pub_lb = {
      create  = var.pub_lb_subnet_create ? "always" : "never",
      newbits = var.pub_lb_subnet_newbits,
      id      = var.pub_lb_subnet_id
    }

    wlsservers = {
      create  = var.wlsserver_subnet_create ? "always" : "never",
      newbits = var.wlsserver_subnet_newbits,
      id      = var.wlsserver_subnet_id
    }

  }

  # Network Security
  nsgs = {
    bastion = { create = var.create_nsgs ? "always" : "never" }
    #operator = { create = var.create_nsgs ? "always" : "never" }
    int_lb = { create = var.create_nsgs ? "always" : "never" }
    pub_lb = { create = var.create_nsgs ? "always" : "never" } #TODO: JOI - Future release include existing Public LB NSG.
    managedserver = {
      create = var.create_nsgs ? "always" : "never",
      id     = var.managedserver_nsg_id
    }
    adminserver = {
      create = var.create_nsgs ? "always" : "never",
      id     = var.adminserver_nsg_id
    }
  }

  #Network Security
  allow_node_port_access           = var.allow_node_port_access
  allow_wlsservers_ssh_access      = var.allow_wlsserver_ssh_access
  allow_wlsservers_internet_access = var.allow_wlsserver_internet_access
  allow_adminserver_ssh_access     = var.allow_adminserver_ssh_access
  allow_bastion_adminserver_access = var.allow_bastion_adminserver_console_access
  allow_bastion_domain_access      = var.allow_bastion_domain_access
  enable_waf                       = var.enable_waf #TODO: JOI - Future release


  allow_rules_internal_lb = var.allow_rules_internal_lb #TODO: JOI - Future release include internal lb rules
  allow_rules_public_lb   = var.allow_rules_public_lb


  # SSH Access
  ssh_public_key      = local.ssh_public_key
  ssh_public_key_path = var.ssh_public_key_path
  ssh_private_key     = sensitive(local.ssh_key_bundle_content)

  #Weblogic Servers Images
  create_domain               = var.create_domain #true
  wlsserver_pools             = var.wlsserver_pools
  image_instance_requirements = local.vm_instance_image_requirements
  wlsserver_image_type        = lower(local.wlsserver_image_type)
  wlsserver_image_id          = local.vm_instance_image_id
  wlsserver_image_os          = var.wlsserver_image_os
  #TODO JOI: wlsserver image os version need to be locked with host found.
  wlsserver_image_os_version = var.wlsserver_image_os_version
  # Development or Release

  vm_script_path = local.vm_scripts_path_selected
  #release = "DEV"
  #Weblogic Server Instance Details
  wlsserver_cloud_init = local.wlsserver_cloud_init
  wlsserver_shape      = var.wlsserver_shape

  #TODO: (joi) pass freeform tags to resource manager and load balancers
  freeform_tags = {
    wlsservers = lookup(var.wlsserver_tags, "freeformTags", {})
  }

  defined_tags = {
    wlsservers = lookup(var.wlsserver_tags, "definedTags", {})
  }

  #DB
  is_vcn_peering            = local.is_vcn_peering
  db_network_compartment_id = local.db_network_compartment_id
  db_existing_vcn_id        = local.db_existing_vcn_id
  db_subnet_id              = local.db_subnet_id

  #Object Storage Archive Repository
  bucket_name          = var.bucket_name
  restore_wls_archives = "none" #all
  await_node_readiness = "none" #all

  #Weblogic Domain Common  - LoadBalancer, labels
  add_load_balancer              = var.add_load_balancer
  db_strategy_is_atp             = local.db_strategy_is_atp
  db_strategy_is_edit_string_atp = local.db_strategy_is_edit_string_atp
  lbs = {
    pub_lb = { create = var.add_load_balancer ? "always" : "never", id = var.existing_load_balancer_id, backends = var.custom_backends }
  }
  lb_shape = {
    pub_lb = { shape = var.load_balancer_shape, min = var.lb_min_bandwidth, max = var.lb_max_bandwidth }
  }



  #Bastion
  create_bastion              = var.create_bastion
  bastion_subnet_cidr         = var.bastion_subnet_cidr
  bastion_shape               = var.bastion_shape
  boot_volume_size            = var.bastion_shape_boot
  bastion_allowed_cidrs       = var.bastion_allowed_cidrs
  bastion_is_public           = var.bastion_is_public
  bastion_public_ip           = null # Ignored when create_bastion = true
  bastion_availability_domain = var.bastion_availability_domain
  bastion_user                = var.bastion_user
  bastion_image_os            = var.bastion_image_os
  bastion_image_os_version    = var.bastion_image_os_version
  bastion_image_type          = var.bastion_image_type # platform/custom
  bastion_image_id            = var.bastion_image_id
  bastion_upgrade             = false
  #bastion_tags = var.bastion_tags

  #datasources
  wls_configured_datasource_text = local.datasources
}
