# Copyright (c) 2024 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v1.0 as shown at https://oss.oracle.com/licenses/upl.

title: "Oracle WebLogic Migration for Oracle Cloud Infrastructure"
description: "Migrate Oracle WebLogic Server to Oracle Cloud Infrastructure"
informationalText: "This stack provisions an OCI Virtual Cloud Network, OCI Compute Instances running a migrated Weblogic Domain, enables a OCI Load Balancer, and restores de necessary Weblogic archives stored in Object Storage"
schemaVersion: 1.1.0
version: "20190304"

source:
  type: quickstart

locale: "en"
variableGroups:
  - title: "Basic Hidden"
    variables:
      - tenancy_ocid
      - region
      - user_ocid
      - fingerprint
      - private_key_path
    visible: false

  - title: "General Configuration"
    variables:
      - domain_name
      - compartment_ocid
      - object_storage_bucket
      - image_mode
      - terms_and_conditions

  - title: "Virtual Cloud Networking"
    variables:
      - use_existent_vcn
      - network_compartment_id
      - wls_existing_vcn_id
      - wls_vcn_name
      - wls_vcn_cidr
      - create_new_subnets
      - subnet_compartment_id

  - title: "WebLogic Server Compute Instance"
    variables:
      - wls_instance_shape
      - wls_visibility
      - ssh_public_key

  - title: "Loadbalancer"
    variables:
      - load_balancer_shape
      - loadbalancer_authorized_cidrs_mgmt
      - loadbalancer_authorized_cidrs_service


  - title: "Bastion Configuration"
    variables:
       - bastion_customize_resource
       - bastion_allowed_cidrs
       - bastion_image_type
       - bastion_image_id
       - bastion_instance_shape
       - bastion_upgrade
       - output_detail
       - ssh_private_key


  - title: "Tagging"
    variables:
      - tag_values


  - title: "Extras Hidden"
    variables:
      - timezone
      - object_storage_bucket
      - instance_private_key
      - state_id
      - ssh_private_key_path
      - ssh_public_key_path
#TODO: JOI Review variables.
      - assign_weblogic_public_ip
      - generate_dg_tag
      - create_service_tag
      - create_policies
      - rms_existing_private_endpoint_id
      - is_rms_private_endpoint_required
      - add_rms_private_endpoint
    visible: false

  - title: "Extras Hidden - Images"
    variables:
      - marketplace_source_images
      - bastion_listing_id
      - bastion_listing_resource_version
      - instance_image_id
      - listing_id
      - listing_resource_version
      - ucm_instance_image_id
      - ucm_listing_id
      - ucm_listing_resource_version
      - use_marketplace_image
    visible: false

  - title: "Extras Hidden - LoadBalancer"
    variables:
      - add_lb_reserved_public_ip_id
      - add_load_balancer
      - backendset_name_for_existing_load_balancer
      - existing_lb_nsg_id
      - existing_load_balancer_id
      - lb_subnet_1_cidr
      - lb_subnet_1_name
      - lb_subnet_1_id
      - lb_subnet_2_name
      - lb_subnet_2_id
      - load_balancer_strategy_existing_subnet
      - load_balancer_strategy_new_subnet
      - is_lb_private
      - add_lb_reserved_public_ip_id
      - lb_reserved_public_ip_id
    visible: false

  - title: "Hidden Bastion Network"
    variables:
      - create_bastion
      - bastion_image_id
      - bastion_availability_domain
      - bastion_image_os
      - bastion_is_public
      - bastion_nsg_ids
      - bastion_public_ip
      - bastion_shape
      - bastion_image_os_version
      - bastion_user
      - subnet_type
      - create_new_vcn
      - create_subnets
#TODO: JOI review what is needed below this.
      - existent_private_subnet_ocid
      - existent_public_subnet_ocid
      - existent_vcn_compartment_ocid
      - existent_vcn_ocid
      - ipv6private_cidr_blocks
      - is_ipv6enabled
      - vcn_cidr_blocks
      - bastion_ssh_private_key
      - existing_bastion_instance_id
      - bastion_subnet_cidr
      - bastion_subnet_id
      - bastion_subnet_name
      - existing_admin_server_nsg_id
      - wls_subnet_name
      - wls_subnet_id
      - wls_subnet_cidr
      - wls_availability_domain_name
      - wait_time_wls_vnc_dns_resolver
      - use_regional_subnet
      - existing_bastion_nsg_id
    visible: false

variables:
  compartment_ocid:
    type: oci:identity:compartment:id
    title: "Compartment"
    description: "The compartment in which to create compute instance(s)"
    required: true

  domain_name:
    type: string
    title: "Domain Name"
    required: true
    description: "Domain name to be restored from Object Storage Archives"

  # Bucket
  object_storage_bucket:
    type: string
    minLength: 1
    maxLength: 16
    title: "Object Storage bucket Title"
    description: "Type the name of the bucket in the specified compartment."
    required: false
    visible: false

  image_mode:
    visible: true
    type: enum
    title: "Image for each Weblogic Server instance"
    description: "The selected image is used when creating each Instance. A BYOL image requires a WebLogic License with valid support contract. UCM images are charged per OCPU/hour for the entitlement and WebLogic support."
    required: true
    enum:
      - "Oracle Weblogic Suite UCM Image"
      - "Oracle WebLogic Server Enterprise Edition UCM Image"
      - "Oracle WebLogic Server BYOL Image"

  terms_and_conditions:
    visible:
      and:
        - eq:
            - ${image_mode}
            - "Oracle WebLogic Server Enterprise Edition UCM Image"
    type: boolean
    default: false
    title: "Terms of use"
    description: "I have reviewed and accept the <a target=\"_blank\" href=\"https://objectstorage.us-phoenix-1.oraclecloud.com/n/axxu7cichsnt/b/terms/o/wlsoci_ee_terms_and_conditions.txt\">Oracle terms of use</a>"
    required: true

#### VCN Configuration variables
  use_existent_vcn:
    type: boolean
    title: "Use existing VCN for Weblogic Instances?"
    description: "Use an already provisioned Virtual Cloud Network and subnets"
    default: false

  wls_existing_vcn_id:
    visible:
      and:
        - use_existent_vcn
    type: oci:core:vcn:id
    dependsOn:
      compartmentId: network_compartment_id
    required: true
    default: ''
    title: "Existing Network"
    description: "An existing Virtual Cloud Network (VCN) in which to create the compute instances, network resources, and load balancers. Existing Virtual Cloud Network can be validated using the network validation script. See <a target=\"_blank\" href=\"https://docs.oracle.com/pls/topic/lookup?ctx=en/cloud/paas/weblogic-cloud/user&id=oci_network_validate\">Validate Existing Network Setup</a>"

  network_compartment_id:
    visible: true
    type: oci:identity:compartment:id
    title: "Network Compartment"
    description: "The compartment where you want to create the network resources such as Virtual Cloud Network, security lists, route tables and gateways."
    required: false
    default: compartment_ocid

  wls_vcn_name:
    visible:
      not:
        - use_existent_vcn
    type: string
    minLength: 1
    maxLength: 255
    pattern: "^[a-zA-Z_]\\w{0,254}$"
    required: true
    title: "Virtual Cloud Network Name"
    description: "The name of the new Virtual Cloud Network (VCN) to create for this service"

  wls_vcn_cidr:
    visible:
      not:
        - ${use_existent_vcn}
    type: string
    default: 10.0.0.0/16
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "Virtual Cloud Network CIDR"
    description: "The CIDR to assign to the new Virtual Cloud Network (VCN) to create for this service"

  subnet_compartment_id:
    visible:
      and:
        - not:
            - use_existent_vcn
        - not:
            - create_new_subnets
    type: oci:identity:compartment:id
    title: "Subnet Compartment"
    description: "The compartment where you have subnets created"
    required: true
    default: compartment_ocid

#  subnet_type:
#    visible:
#      and:
#        - not:
#            - ${use_existent_vcn}
#        - not:
#            - ${create_new_subnets}
#    type: enum
#    title: "Subnet Type"
#    description: "Current version Private Subnet.. Warning - If you select a public subnet, ensure to limit the CIDR range to access WebLogic administration console ports (defaults are 7001 and 7002 for http and https)."
#    enum:
#      - "Use Private Subnet"
#    default: "Use Private Subnet"
#
#  subnet_span:
#    visible:
#      and:
#        - not:
#            - ${use_existent_vcn}
#        - not:
#            - ${create_new_subnets}
#    type: enum
#    title: "Subnet Span"
#    description: "Choose between regional and AD specific subnets"
#    enum:
#      - "Regional Subnet"
##      - "AD Specific Subnet"
#    required: true
#    default: "Regional Subnet"

  #  existent_oci_vcn_compartment_ocid:
  #    type: oci:identity:compartment:id
  #    title: "Existent VCN Compartment"
  #    required: true
  #    default: compartment_ocid
  #    visible: true
  #
  #  existent_oci_vcn_ocid:
  #    type: oci:core:vcn:id
  #    title: "Existent VCN with OCI Resources"
  #    required: true
  #    dependsOn:
  #      compartmentId: compartment_ocid
#######################################
### End : VCN Configuration Variables
######################################
#######################################
### Section : Common Configuration Variables
######################################
  ssh_public_key:
    type: oci:core:ssh:publickey
    title: "Import your own SSH public key"
    additionalProps:
      allowMultiple: true
    required: false
    pattern: "((^(ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)(,((ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)*$"
    visible: true

  wls_instance_shape:
    type: oci:core:instanceshapewithflex:name
    title: "Select a flex or fixed shape for all Weblogic compute instances"
    required: true
    dependsOn:
      compartmentId: compartment_ocid
    # visible:
    #   and:
    #     - create_new_oke_cluster
    #     - show_advanced

  wls_visibility:
    type: enum
    enum:
      - "Private"
    title: "Oracle Weblogic Managed Server Instances will be hosted in private subnet(s)"
    required: true
    default: "Private"
  #######################################
  ### Section : Bastion Configuration Variables
  ######################################
  ssh_private_key:
    type: oci:core:ssh:publickey
    title: "Import your own SSH Private key"
    description: "Note: This SSH Private Key will only be used to connect to Bastion host to perform management tasks. You must remove it after provision and testing has completed."
    additionalProps:
      allowMultiple: true
    required: true
    pattern: "((^(ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)(,((ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)*$"
    visible: true

  bastion_instance_shape:
    type: oci:core:instanceshapewithflex:name
    title: "Select a flex or fixed shape for the Bastion compute instance"
    required: true
    dependsOn:
      compartmentId: compartment_ocid
    visible:
        bastion_customize_resource

  bastion_allowed_cidrs:
    type: array
    title: "List of CIDR blocks to allow SSH access to the bastion host"
    required: false
    description: "NOTE: Default is empty i.e. no access permitted. Allow access from anywhere with '0.0.0.0/0'. Specific network W.X.Y.Z/NN or individual host by IP followed by /32 X.X.X.X/32"
    items:
      type: string
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    uniqueItems: true

  bastion_customize_resource:
    type: boolean
    default: false
    title: "Customize Bastion Instance"
    description: "Select Option if you want to customize further. Default Bastion configuration:  OCPUs: 1, Mem: 5Gb  Shape:VM.Standard.E4.Flex"
    visible: true
    required: true

  bastion_image_type:
    visible:
       bastion_customize_resource
    type: enum
    enum:
      - "Marketplace"
      - "Platform"
      - "Custom"
    title: "Select the type of Image for Bastion Instance"
    default: "Marketplace"
    required: false

  bastion_image_id:
    type: string
    required: true
    title: "Instance Image OCID"
    visible:
      and:
        - bastion_customize_resource
        - eq:
            - bastion_image_type
            - "Custom"
    pattern: ^ocid1.image.*$
    dependsOn:
      compartmentId: compartment_ocid

  bastion_upgrade:
    type: boolean
    default: false
    title: "Upgrade Bastion Packages?"
    description: "Whether to upgrade bastion packages after provisioning."
    visible:
        bastion_customize_resource
    required: false

  output_detail:
    type: boolean
    default: false
    title: "Verbose Output"
    description: "Whether to include detailed output in state."
    visible:
      bastion_customize_resource
    required: false
#  bastion_instance_visibility:
#    type: enum
#    enum:
#      - "Private"
#    title: "Bastion will be hosted in public or private subnet(s)"
#    required: true

#  create_bastion_subnet:
#    type: boolean
#    title: "Creates a new Bastion Subnet."
#    required: true

#  bastion_visibility:
#    type: enum
#    enum:
#      - "Private"
#      - "Public"
#    title: "Bastion will be hosted in public or private subnet(s)"
#    required: true
  #######################################
  ### End : Bastion Configuration Variables
  ######################################
  #Section: LoadBalancer Configuration
  ######################
  load_balancer_shape:
    type: enum
    enum:
      - "flexible"
    title: "Select a shape for the load balancer"
    visible:
      and:
        - show_advanced
  loadbalancer_authorized_cidrs_service:
    type: array
    title: "Authorized list of Network Addresses to connect Loadbalancer Application Ports"
    required: false
    description: "Type each network address in cidr format Y.Y.Y.Y/XX. Click after each type to be registered in the text area. Example Format: Network 192.168.1.0/24 or individual host by IP/32 . ex X.X.X.X/32"
    items:
      type: string
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    uniqueItems: true
    default: [0.0.0.0/0]

  loadbalancer_authorized_cidrs_mgmt:
    type: array
    title: "Authorized list of Network Addresses to connect to Weblogic Console and Admin Ports exposed on the Loadbalancer"
    required: true
    description: "Type each network address in cidr format Y.Y.Y.Y/XX. Click after each type to be registered in the text area. Example Format: Network 192.168.1.0/24 or individual host by IP/32 . ex X.X.X.X/32"
    items:
      type: string
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    uniqueItems: true
  #########################
  ### End: LoadBalancer Configuration
  #######################################
  tag_values:
    type: oci:identity:tag:value
    title: Tag Resources
    required: false
    visible: show_advanced
    dependsOn:
      compartmentId: compartment_ocid

